const RAW = "https://raw.githubusercontent.com/Ahadmtv/ui-generator/main";
export const assets = {
  logo: `${RAW}/src/images/logo-80.webp`,
  wordmarkLight: `${RAW}/src/images/wordmark-light.webp`,
  wordmarkDark: `${RAW}/src/images/wordmark-dark.webp`,
  appPreview380: `${RAW}/public/app-preview-380.webp`,
  appPreview760: `${RAW}/public/app-preview-760.webp`,
  myket: `${RAW}/src/images/miket.png`,
  bazaar: `${RAW}/src/images/bazar.png`,
  featureRecipes: `${RAW}/src/images/feature-recipes.webp`,
  featureRecipesSmall: `${RAW}/src/images/feature-recipes-480.webp`,
  featurePlanner: `${RAW}/src/images/feature-planner.webp`,
  featurePlannerSmall: `${RAW}/src/images/feature-planner-480.webp`,
  featureShopping: `${RAW}/src/images/feature-shopping.webp`,
  featureShoppingSmall: `${RAW}/src/images/feature-shopping-480.webp`,
  featurePantry: `${RAW}/src/images/feature-pantry.webp`,
  featurePantrySmall: `${RAW}/src/images/feature-pantry-480.webp`,
  featureWorld: `${RAW}/src/images/feature-world.webp`,
  featureWorldSmall: `${RAW}/src/images/feature-world-480.webp`,
  verticalMockup: `${RAW}/src/images/vertical-mockup.webp`,
  article1: `${RAW}/src/images/article-1.webp`,
  article1Small: `${RAW}/src/images/article-1-450.webp`,
  article2: `${RAW}/src/images/article-2.webp`,
  article2Small: `${RAW}/src/images/article-2-450.webp`,
  article3: `${RAW}/src/images/article-3.webp`,
  article3Small: `${RAW}/src/images/article-3-450.webp`,
  og: `${RAW}/public/og-image-1200x630.png`,
  icon192: `${RAW}/public/android-chrome-192x192.png`,
  icon512: `${RAW}/public/android-chrome-512x512.png`,
  appleTouch: `${RAW}/public/apple-touch-icon.png`,
  favicon32: `${RAW}/public/favicon-32x32.png`
} as const;
